### PR TITLE
something like that?

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Review by wm75 — COMMENTED** [review]
I guess I don't want to make that guarantee cause we should only do if this is truly public, findable data? The Viral Beacon project might not want to have stuff in their database that just disappears after a while.

What about the straightforward solution of *publishing* the result histories in Galaxy (not just have them accessible)?
Then if we think the data also qualifies for Viral Beacon we triggering also the ftp export?

**Comment by bgruening** [comment]
> I guess I don't want to make that guarantee cause we should only do if this is truly public, findable data? The Viral Beacon project might not want to have stuff in their database that just disappears after a while.
> 
> What about the straightforward solution of _publishing_ the result histories in Galaxy (not just have them accessible)?
> Then if we think the data also qualifies for Viral Beacon we triggering also the ftp export?

If it's not public data and assuming Beacon doesn't want to have it, it's not in one of the ENA folders but maybe in a "extra" folder on the FTP. So this decision can be taken by the Beacon people to not include data in the "extra" folder.

The idea is just we push everything out make it available and others (including vBeacon) are then able to decide which data they use or not. I think this could work very well as long as we make clear from where the data is coming.

**Comment by wm75** [comment]
Ok, with the extra folder that makes some sense then. Publishing the histories in Galaxy would still be a good complementary approach, or not?

**Comment by bgruening** [comment]
> Publishing the histories in Galaxy would still be a good complementary approach, or not?

Yes!

**Pull request merged**
