### PR TITLE
Create pre_B117_batch

### PR DESCRIPTION
**Pull request by wm75**
The "COG-UK pre-B.1.1.7 batch" from https://www.biorxiv.org/content/10.1101/2021.03.25.437046v1

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Filename could be improved maybe?

**Comment by wm75** [comment]
Guess it's not an absurd history name, is it? That's the important bit. Or do we want to use the files in this repo to document precisely what we've analyzed?

**Comment by bgruening** [comment]
I was just wondering if that is an ideal example, especially if we point people in our readme to these example names.

I don't have a strong feeling, was just wondering. Please go ahead! :)
This is super cool to see!

**Comment by wm75** [comment]
I'm going to leave the filename as it is. There is a descriptive header line within the file, which describes exactly what this is about.

**Pull request merged**
